name: Publish Javadoc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '22'
        distribution: 'adopt'

    - name: Generate Javadoc
      run: |
        javadoc -d docs/ -subpackages app

    - name: Deploy Javadoc to GitHub Pages
      run: |
        git config --global user.name 'BOTFloindil'
        git config --global user.email 'floindil@gmail.com'

        # Fetch and checkout gh-pages branch
        git fetch origin gh-pages
        git checkout gh-pages || git checkout --orphan gh-pages

        # Remove old Javadoc files
        rm -rf *

        # Copy new Javadoc files from the main branch
        cp -r ../docs/* .

        # Add and commit changes if there are any
        git add .

        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Automated Javadoc deployment"
          git push origin gh-pages --force
        else
          echo "No changes to commit"
        fi
